version: '3.8'
services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - wordpress    
    ports:
      - "80:80"
      - "443:443"
    networks:
      wordpress-network:
        aliases:
          - webserver      
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    networks:
      wordpress-network:
        aliases:
          - certbot     
      
  wordpress:
      image: wordpress
      depends_on:
        - mariadb        
      links:
      - mariadb:mysql
      environment:
      - WORDPRESS_DB_PASSWORD=${MARIADB_PWD}
      ports:
      - "80"
      volumes:
        - type: volume
          source: wordpress-data
          target: /var/www/html
          volume:
            nocopy: true
      networks:
        wordpress-network:
          aliases:
            - wordpress
  mariadb:
      image: mariadb
      environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PWD}
      - MYSQL_DATABASE=wordpress
      volumes:
        - type: volume
          source: db-data
          target: /var/lib/mysql
          volume:
            nocopy: true     
      networks:
        wordpress-network:
          aliases:
            - db     
volumes:
  wordpress-data:
  db-data:

networks:
  wordpress-network:
